version: "3.4"
services:
    webserver:
        container_name: lamp-docker-nginx
        build: ./webserver
        ports:
            - "8011:80"
        volumes:
            - ./projects:/var/www/html
            - ./webserver/logs:/var/log/nginx
        links:
            - php

    php:
        container_name: lamp-docker-php
        build: ./php
        image: php:7.2.8-fpm
        volumes:
            - ./projects:/var/www/html
        links:
            - db
        env_file: ./php/.env

    db:
        image: mysql:5.7
        ports:
            - "3399:3306"
        container_name: lamp-docker-db
        env_file: ./db/.env
